### ISSUE TITLE
Import Preview Image?

### ISSUE THREAD

**Issue by contempoinc** [richtabor/MerlinWP#49]
@richtabor @primozcigler Has this been implemented yet? I specified the URL for each but I'm not seeing the preview images displayed anywhere just the plain old select drop?

**Comment by contempoinc** [comment]
Couple examples selecting different imports:

![image](https://user-images.githubusercontent.com/686530/36752750-dce6132a-1bb8-11e8-9837-b9becad8b448.png)

![image](https://user-images.githubusercontent.com/686530/36752780-f7952de6-1bb8-11e8-84eb-7020d77c23fb.png)

**Comment by contempoinc** [comment]
I also fixed the "Advanced" drawer trigger position with a little CSS, relative position, and top 14px.

**Comment by capuderg** [comment]
Hi @contempoinc,

no, the preview images are not yet being used, but the data is already prepared, so it's a matter of UI and UX implementation, just like the demo dropdown and "advanced" dropdown design.

This should be solved before the official version 1 comes out.

**Comment by primozcigler** [comment]
I believe that @capuderg has been in touch with @richtabor about this enhancement. For now, we've prioritized that the functionality is there, but the UI desires some facelift.

**Comment by richtabor** [comment]
Yea, I'm planning to take a look at multi-demo import selections. 👍

**Comment by contempoinc** [comment]
@capuderg Agreed, its definitely going to be a tricky one to solve since you want to keep it simple, not increase the overall height of the wizard step to step but there's got to a nice clean way to do it, couple ideas:

- Add an image icon to the demo select when clicked it pops a modal open (similar to Wordpress core "Theme details") but smaller with the image and small description using the import_notice from the config. 
- Another option when hovering the demos in the select a simple window pops up with the image similar to TF on hovering theme thumbs.

**Comment by contempoinc** [comment]
Threw together a quick mockup

![merlin-demo-previews](https://user-images.githubusercontent.com/686530/36804659-11aaba5e-1c70-11e8-8b86-7d9cdbafd632.png)

**Comment by contempoinc** [comment]
And a quick mockup of the preview image open with title and short description.

![merlin-demo-previews-open](https://user-images.githubusercontent.com/686530/36805308-e7cc70e0-1c71-11e8-94ac-dcd0c105dc96.png)

**Comment by capuderg** [comment]
@richtabor I've pushed the data with basic styling for this multi demo import preview in this branch `improve-multi-demo-import-selection`. For now I've just added a "box" below the select control, which changes, if you select different demo imports.

The "box" displays only, if the `import_preview_image_url` parameter is set in the predefined demo import filter.

The "box" displays the image, the notice and the link to the demo page.

I'm not sure, what the best UX would be for this "box" and for the select control. I do like the popup solution provided above, but I don't like the hover suggestion, that triggers it (in the option of the select control). What happens on mobile? How will you trigger the hover (or click) on mobile inside the select option?

My current implementation is very basic (and makes the wizard content import step very tall), but I just wanted to push this feature forward. The data is prepared, now it's just a matter of how we present it...

Any ideas are welcome!

**Comment by richtabor** [comment]
@capuderg I touched up the multi-import process styling, if there is no image. The image feature is a bit trickier and I'm still not sure on the best approach.  
<img width="530" alt="screen shot 2018-04-15 at 11 51 12 am" src="https://user-images.githubusercontent.com/1813435/38780377-57352bd4-40a3-11e8-8c48-40a42b2ffeb6.png">

**Comment by richtabor** [comment]
@capuderg Should we go ahead and do a PR with the better selector as pictured above? Then revisit demo images eventually?

**Comment by capuderg** [comment]
@richtabor I think the image part is very important for the multi demo import, so I wouldn't create a PR just yet. Would rather solve the whole thing in this PR.

I know, it's a bit trickier, but once this is done, we are looking at a good rounded product.

**Comment by richtabor** [comment]
Alright, though I'm not personally invested in multi-demo support, so this is realistically lower on my priority list. I'll see if I can squeeze in a couple hours for it, but I don't know when I can get a solid PR with image support.

**Comment by JiveDig** [comment]
Assuming we use MerlinWP for our theme demo improve, multi-demo support is critical. We’d get by with a drop-down, but thumbnail support would be great as well. 

What if instead of a drop down it was a button that launched a big overlay with clickable thumbnails to choose which demo to import?

**Comment by JiveDig** [comment]
Another note, that the select with inner preview link (as in @contempoinc's mockups) is a decent solution as well. If there are more then a few demo options a grid of thumbnails would be much easier for a user IMO, but maybe out use-case is an edge-case.

**Comment by capuderg** [comment]
@JiveDig any help with the implementation is more than welcome (PR welcomed :) ).

I'm still not sure what would be the best implementation, that's why this feature is also not progressing as it should.

For now we will probably just improve the select dropdown for multi demo import.

@richtabor I've added a spinner next to the select dropdown, so user will know something is change-ing (new import option "parts" (content, widget, customizer,...) have to be loaded form server). And I've also removed the basic preview box, so we can merge this new select dropdown to the master.

The only issue I have with this design: https://github.com/richtabor/MerlinWP/issues/49#issuecomment-381416544 is, that the "down arrow" icon is missing at the right side of the select control, which would usually indicate a select control. What do you think? When you look at the control, do you know instantly that it's a select (dropdown) control? And what you need to do?

Wouldn't a text above the control ala "select the demo you want to import" and a dropdown control be more straightforward?

Once this is resolved, I would merge it to the master, so that we at least have a better dropdown.

**Comment by JiveDig** [comment]
Just submitted a PR for this to at least get it tolerable for launch.

<img width="421" alt="screen shot 2018-10-03 at 2 10 46 pm" src="https://user-images.githubusercontent.com/540990/46430235-6905dd00-c716-11e8-8661-4635985ce7d7.png">

**Comment by richtabor** [comment]
I've updated the icon and adjusting the styling a bit to fit more.  

<img width="654" alt="screen shot 2018-10-04 at 6 24 04 pm" src="https://user-images.githubusercontent.com/1813435/46507419-65518380-c806-11e8-9699-e3c4e36abf58.png">

**Comment by JiveDig** [comment]
Figured you'd probably give it a once over... even better! Nice.
